### ISSUE TITLE
Question: ec2 ignore all changes

### ISSUE THREAD

**Issue by vladborovtsov** [hazelops/terraform-aws-ec2-openvpn-connector#10]
https://github.com/hazelops/terraform-aws-ec2-openvpn-connector/blob/ccb8da1b046887524074fdf59be7c2d6273aa95d/main.tf#L48

What was the reason to keep EC2 instance immutable once created? This means you cannot alter its settings, like security groups, subnets, etc

**Comment by DimmKirr** [comment]
We can try to ask @igorkotof, let's see if he responds.

It's been an while since [this commit](https://github.com/hazelops/terraform-aws-ec2-openvpn-connector/commit/b532455f60dcdae9dc9b807e566b857c66840790) from 2021.

There is a chance it was a workaround for something and it might be better to stop ignoring it.

**Comment by igorkotof** [comment]
@vladborovtsov I do not remember the reason of this workaround. Please go ahead to remove it or even make it via condition. Thx!

**Comment by vladborovtsov** [comment]
Apparently I can see the reason now. Change in template or user data causing instance to be re-created, so its public IP will change (in case it wasn't using EIP) and rootfs will be wiped. Such behaviour could be unwanted. 

I think it would be more fair to have 
```
  lifecycle {
    ignore_changes = [user_data, key_name]
  }
```

**Comment by DimmKirr** [comment]
@vladborovtsov,
Thank you for looking into this!
I agree, feel free to submit a PR 🙂
